[build]
rustc-wrapper = "/Users/sergibli/.cargo/bin/clippy-driver"
target = "riscv64gc-unknown-none-elf"

[env]
CLIPPY_TESTS = "true"

[net]
git-fetch-with-cli = true

[target.riscv64gc-unknown-none-elf]
runner = "riscv64-unknown-elf-gdb"
rustflags = ["-C", "link-arg=-Tlink.x"]
